Implemented ProductDao and Use ProductDao on PLP
DaniilTuruhanov/phoneshop-servlet-api pull request #1
Opened 2019-10-27 20:33 UTC by DaniilTuruhanov

2019-10-28 07:47 UTC, Alastifer requested changes

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    }
зачем этот метод?

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productList.add(new Product(13L, "simsxg75", "Siemens SXG75", new BigDecimal(150), usd, 40, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Siemens/
вынеси в отдельный метод

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .filter((p) -> p.getId() == id && p.getCurrency() != null && p.getStock() > 0)
в лямбда название переменной пиши нормальное. И не ставь () если один параметр

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        }
Возвращаем Optional

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    @Override
пустую строку добавь

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    public synchronized List<Product> findProducts(){
пробел между ) и {

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .filter((p)->p.getCurrency()!=null && p.getStock()>0)
название переменной

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        .toList());
зачем такое форматирование? можно в одну строку

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        product.setId(productList.size()>0 ? productList.size() + 1 : 1L);
Юзай для генерации id UUID

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        product.setId(productList.size()>0 ? productList.size() + 1 : 1L);
пробелы добавь productList.size()>0

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productList.add(product);
что будет, если мы сохраняем продукт с уже существующей id?

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        }
кому ты собираешься out показывать?

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        }
И зачем тут ловишь исключение?

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    /**
убери все комменты

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    }
equals и hashCode сделать по первичному ключу

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      private String code;
оставь либо code либо id

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    private ArrayListProductDao arrayListProductDao = new ArrayListProductDao();
нужно создавать во время инициализации сервлета

2019-10-28 07:47 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        request.setAttribute("products",arrayListProductDao.getProductList());
пробел

2019-10-28 07:47 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
>          verify(requestDispatcher).forward(request, response);
проверь есть ли продукты в реквесте

2019-10-28 07:47 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
> +    private final static String path="/WEB-INF/pages/productList.jsp";
пустую строку добавь

2019-10-28 07:52 UTC, DaniilTuruhanov commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    }
для того чтобы использовать в сервлете и использовать в атрибуте products

2019-10-28 07:58 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    }
у тебя для сервлета есть findProducts()

2019-10-31 10:08 UTC, Alastifer requested changes

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +import java.util.*;
wildcard убери

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .filter(product -> product.getId().equals(id) && product.getPrice() != null && product.getStock() > 0)
проверка на price и stock только когда все продукты достаешь

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            productList.remove(optionalProduct.get());
посмотри метод set

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            productList.add(product);
кривое форматирование

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            product.setId(UUID.randomUUID().getMostSignificantBits());
сделай id стрингой и передавай весь сгенерированный uuid

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .findAny();
это работает как getProduct. Не делай дубликат кода

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    private volatile Long id;
volatile на не нужен

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
>  package com.es.phoneshop.model.product;
Где синхронизация?

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        }
зачем здесь синхронизация, если она в дао должна быть?

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Service.java
> +public class Service {
название не о чем не говорит. Лучше ProductService

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/sortResources/Comparing.java
> +package sortResources;
именование пакетов так не делают. sort.resources - да. Но не понятно что значит resources

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
> +    public ProductDao productDao;
почему public?

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
> +    servletContextEvent.getServletContext().setAttribute("productDao",productDao);
во первый, тут нужно делать инициализацию сервиса, а не дао. Во вторых нужно делать singltons

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        request.setAttribute("products", service.productListFromDao(query, comparing.field, comparing.upOrDown));
ты либо передавай весь comparing сервису, либо он вообще не нужен

2019-10-31 10:08 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        service = new Service();
Сервис и дао будут синглтонами

2019-11-10 09:05 UTC, Alastifer requested changes

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    private static volatile ArrayListProductDao arrayListProductDao;
volatile убери

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        synchronized (id) {
нельзя делать синхронизацию просто по строке. погугли

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .filter(product -> query == null || query.trim().equals("") || containsAll(product, query)  /*!Collections.disjoint(Arrays.asList(product.getDescription().split(" ")), Arrays.asLi
комменты поубирай

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        synchronized (Product.class) {
так не делаем синхронизацию. это тоже самое что в методе прописать synchronize

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .filter(product -> product.getPrice() != null && product.getStock() > 0)
дубликат кода из findProducts()

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    })
в отдельный метод

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            } else
посмотри в метод листа set

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            } else
где скобки для else?

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/PriceRecord.java
> +    private Calendar data;
LocalDate

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +    private static volatile ProductService productServiceDao;
зачем в сервисе volatile?

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +            synchronized (ProductService.class) {
зачем тут синхронизация?

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +        else {
соблюдай форматирование

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +    public List<Product> findProductsFromDao() {
зачем fromDao?

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +    public List<Product> findProductsFromDao(String query, String sortByField, String comparing) {
зачем fromDao?

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +    private static volatile ProductService productServiceDao;
именование переменных

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/PriceHistoryServlet.java
> +           Product product=productService.getProductFromDao(idProduct);
форматирование

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/PriceHistoryServlet.java
> +            req.getRequestDispatcher("/WEB-INF/pages/errorPage.jsp").forward(req, resp);
чекал этот момент?

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductDetailPageServlet.java
> +        req.getRequestDispatcher("/WEB-INF/pages/productPage.jsp").forward(req, resp);
два раза вызовится requestDispatcher если вылетит исключение

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
ajax такой через post не делается

2019-11-10 09:05 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
> +        arrayListProductDao.save(new Product("13L", "Siemens SXG75", new BigDecimal(150), usd, 40, new ArrayList<PriceRecord>(Arrays.asList(new PriceRecord(new GregorianCalendar(2019, 0, 10), new Big
сделай в дао инициализацию

2019-11-10 09:05 UTC, Alastifer commented on src/main/webapp/WEB-INF/pages/errorPage.jsp
> +<!-- как использовать русский текст-->
убери

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    private ArrayListProductDao productDao= ArrayListProductDao.getInstance();
форм

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertTrue(!productDao.findProducts(null, null, null).isEmpty());
что за "!"?

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void testFindProductsHaveSomeResults()
именование переменных

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +
убери

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals(productDao.findProducts(null, null, null),new ArrayList<Product>(Arrays.asList(new Product("1L", "Samsung Galaxy S", new BigDecimal(100), usd, 100, new ArrayList<PriceRecord>(Arr
форм

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals(productDao.getProduct("1L").get(),new Product("1L", "Samsung Galaxy S", new BigDecimal(100), usd, 100, new ArrayList<PriceRecord>(Arrays.asList(new PriceRecord(new GregorianCalen
выноси продукты как отдельные поля

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ProductServiceTest.java
> +    private static ArrayListProductDao productDao = ArrayListProductDao.getInstance();
моком

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/PriceHistoryServletTest.java
> +        verify(request).setAttribute("priceHistory", productService.getProductFromDao("1L"));
???

2019-11-10 09:05 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductDetailPageServletTest.java
> +    private RequestDispatcher requestDispatcher;
пустые строки добавь

2019-11-10 10:13 UTC, DaniilTuruhanov commented on src/test/java/com/es/phoneshop/model/product/ProductServiceTest.java
> +    private static ArrayListProductDao productDao = ArrayListProductDao.getInstance();
а зачем здесь мок
если это не сервлет

2019-11-10 17:06 UTC, Alastifer requested changes

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        synchronized (this) {
зачем тут синхронизация?

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        return product2.getPrice().compareTo(product1.getPrice());
в отдельный метод

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +            synchronized (ProductService.class) {
?

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +                    productService = new ProductService();
скобки где?

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/SortProductServlet.java
> +        printWriter.flush();
разделяй код на блоки для удобочитаемости

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
>          arrayListProductDao = arrayListProductDao.getInstance();
зачем присвоение?

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
> +    private static ArrayListProductDao arrayListProductDao;
зачем тут поле?

2019-11-10 17:06 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
>          arrayListProductDao = arrayListProductDao.getInstance();
инициализируй также сервис

2019-11-10 17:06 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      public void testGetProduct() {
именование норм сделай

2019-11-10 17:06 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ProductServiceTest.java
>      public void testFindProducts() {
именовние

2019-11-11 08:14 UTC, Alastifer requested changes

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        }
убери синхронизацию

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                })
в отдельный метод

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productList = findProducts();
сириасли?

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        synchronized (new SynchronizeMap().findKey(id)) {
SynchronizeMap().findKey(id) сделай статик метод, чтобы объект по кучу раз не создавать

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            if (productList.contains(product)) {
98 и 100 строки. Не думаешь, что сет будет выполняться каждый раз, если id == null?

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        synchronized (new SynchronizeMap().findKey(product.getId())) {
подумай что делать, если id продукта null

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .findAny();
дублирование кода

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        return (this.id==product.getId());
форматирование

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ProductService.java
> +            if (productService == null) {
?

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/ProductDetailPageServlet.java
> +
убери строку пустую

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/com/es/phoneshop/web/SortProductServlet.java
> +        PrintWriter printWriter=resp.getWriter();
форм

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
> +import java.awt.*;
what?

2019-11-11 08:14 UTC, Alastifer commented on src/main/java/sampledata/ProductDemodataServletContextListener.java
> +        HttpSessionListener, HttpSessionAttributeListener {
зачем имплементить столько листенеров?

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertFalse(productDao.findProducts().isEmpty());
проверяй, что там то количество продуктов что нужно, и продукты те, что засетал

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        productDao.setProductList(new ArrayList<>());
Collections.emptyList()

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      }
где тест на лист продуктов с нулевым стоком?

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        Product product = new Product("1L", "Samsung Galaxy S", new BigDecimal(100), usd, 100, new ArrayList<PriceRecord>(Arrays.asList(new PriceRecord(LocalDate.of(2019, 1, 10), new BigDecimal(100),
зачем два раза создавать один и тот же продукт?

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    public void returnProductWhenProductDoesNotExistInDao() {
название не смущает? результат то у тебя с названием не совпадает

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        ArrayList<Product> findProductArrayList = new ArrayList<>(Arrays.asList(new Product("1L", "Samsung Galaxy S", new BigDecimal(100), usd, 100, new ArrayList<PriceRecord>(Arrays.asList(new Price
зачем два листа?

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertTrue(productDao.getProductList().equals(productArrayList));
лист чекает еще и на порядок элементов. Такое себе решение

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ProductServiceTest.java
> +        Currency usd = Currency.getInstance("USD");
зачем это?

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ProductServiceTest.java
> +        assertFalse(productService.findProducts().isEmpty());
ты же тут так ничего и не сетаешь. Мок же не засетал

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ProductServiceTest.java
> +        ArrayList<Product> findProductArrayList = new ArrayList<>(Arrays.asList(new Product("1L", "Samsung Galaxy S", new BigDecimal(100), usd, 100, new ArrayList<PriceRecord>(Arrays.asList(new Price
ArrayList<Product> findProductArrayList . Зачем именно ArrayList?

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/model/product/ProductServiceTest.java
> +        }
исключение через аннотации ловятся

2019-11-11 08:14 UTC, Alastifer commented on src/test/java/com/es/phoneshop/web/ProductDetailPageServletTest.java
> +        when(productService.getProduct(idProduct.substring(idProduct.lastIndexOf("/") + 1))).thenReturn(product);
не чекаешь разбиение url

2019-11-12 10:31 UTC, Alastifer requested changes

2019-11-12 10:31 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        productList.add(new Product("13L", "Siemens SXG75", new BigDecimal(150), usd, 40, new ArrayList<>(Arrays.asList(new PriceRecord(LocalDate.of(2019, 1, 10), new BigDecimal(150), usd), new Price
в отдельный метод

2019-11-12 10:31 UTC, Alastifer commented on src/main/java/com/es/phoneshop/model/product/SynchronizeMap.java
> +        }
мне вот интересно как ты потом это id искать будешь. Её же ни у одного продукта не будет

2019-11-13 08:28 UTC, merged